### ISSUE TITLE
Add extra requirements on the Password CRD.

### ISSUE THREAD

**Issue by bmoussaud** [carvel-dev/secretgen-controller#110]
**Describe the problem/challenge you have**
The `secretgen.k14s.io/v1alpha1/Password` allows to specify the length of the generated password only. Unfortunately, external resources may ask to have other requirements such as: `Your password must contain characters from three of the following categories – English uppercase letters, English lowercase letters, numbers (0-9), and non-alphanumeric characters (!, $, #, %, etc.).` or `Your password must be at least 8 characters and at most 128 characters`

**Describe the solution you'd like**
Add extra properties to manage these requirements. The password crd can look like
```yaml
apiVersion: secretgen.k14s.io/v1alpha2
kind: Password
metadata:
  name: my-constrained-long-user-password
spec:
  length:
      min: 8
      max: 128
  categories:
     - name: uppercase        #pre-defined category
        min: 2
     - name: lowercase        #pre-defined category + min:1 default values                                              
     - name: my-custom-set
        min: 3
        available: ['!', '$', '#', '%']
```
---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you would like to work on this issue.
