### ISSUE TITLE
`vendir` is unable to consume `latest` github release artifacts

### ISSUE THREAD

**Issue by scothis** [carvel-dev/secretgen-controller#157]
**What steps did you take:**
```yaml
apiVersion: vendir.k14s.io/v1alpha1
kind: Config
directories:
- path: distributions/carvel
  contents:
  - path: secretgen-controller
    githubRelease:
      slug: vmware-tanzu/carvel-secretgen-controller
      latest: true
      assetNames:
      - package.yml
```

**What happened:**
```txt
vendir: Error: Syncing directory 'distributions/carvel':
  Syncing directory 'secretgen-controller' with github release contents:
    Finding checksums in release notes:
      Expected to find sha256 checksum for file 'package.yml'
```

**What did you expect:**
to resolve the `package.yml` release artifact

**Anything else you would like to add:**

The digests for the `latest` release `0.12.0` look like:

```txt
59c60670b23aa2f2c53d6a17a643026c854f86d2ae2e402bc57c121d22ec15c8  ./tmp/release.yml
61432bcb914b779243e38da9b1b78ce94065c80735775b209b56d096b858fb65  carvel-artifacts/packages/secretgen-controller.carvel.dev/package.yml
8f185deaa02964663bc3cedcb7c0af46151676e7c2abc2b69ff04178f87f28fe  carvel-artifacts/packages/secretgen-controller.carvel.dev/package-metadata.yml
```

The digests for 0.11.0 look like:

```txt
5c95408656d898f724df7a29ec4052762a94711a8677637625fbb770af2f3cf4  release.yml
aa1326743e61eb8e9e1122668a9434961a47c36982b65e4d33cc08eab0618dd5  package.yml
55338cd490a6932c857e2035ed552b0a21e07bd2f0a46d4f5d0d2419b2323333  package-metadata.yml
```

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you want to help working on this issue.
