### ISSUE TITLE
Feature: match allow on namespace annotations

### ISSUE THREAD

**Issue by devthejo** [carvel-dev/secretgen-controller#348]
**Describe the problem/challenge you have**
We have multi-tenant clusters where isolation is done by rancher. The mechanism is simple, anyone is scoped in a rancher project, anyone can create new namespace and scope it in it's project scope by adding an annotation that is matching the project id. To summarize this annotation is the guarantee that this namespace will not be accessed by another tenant.
In our dev cluster, we have unpredictable new namespace that will be created for review environments and we want be able to use SecretImport in them, but the constraint in SecretExport based on the destination namespace is not sufficient to address our case.

**Describe the solution you'd like**
We would like be able to specify `ToNamespaceAnnotations` as following, instead of `ToNamespace` on `SecretExport`
```yaml
kind: SecretExport
metadata:
  name: user-password
  namespace: user1
spec:
  toNamespaceAnnotations:
    projectId: my-project-id
```

This could also be
```yaml
kind: SecretExport
metadata:
  name: user-password
  namespace: user1
spec:
  toNamespaceAnnotationKey: projectId
  toNamespaceAnnotationValue: my-project-id
```

**Anything else you would like to add:**
I can try to make a PR if this feature is welcome :-)

---
Vote on this request

This is an invitation to the community to vote on issues, to help us prioritize our backlog. Use the "smiley face" up to the right of this comment to vote.

👍 "I would like to see this addressed as soon as possible"
👎 "There are other more important things to focus on right now"

We are also happy to receive and review Pull Requests if you would like to work on this issue.

**Comment by neil-hickey** [comment]
hi @devthejo , thanks for submitting! 

- Is this annotation specific to rancher or your use-case? What does the annotation look like?
- I'm not very familiar with rancher, is this "tenant via annotation" a standard part of rancher?

I'm not opposed to you making the PR, I just want to make sure that this feature would be useful for the project and not just for your particular use-case if it is specific to your environment.

**Comment by devthejo** [comment]
hi @neil-hickey, thanks for your reactivity!

> - Is this annotation specific to rancher or your use-case? What does the annotation look like?
> - I'm not very familiar with rancher, is this "tenant via annotation" a standard part of rancher?

This is the way rancher do, yes we can call this "tenant via annotation" and this feature could be useful for any user of `rancher` that want to use `secretgen-controller`.

This is how it's look like:

```yaml
apiVersion: v1
kind: Namespace
metadata:
  annotations:
    field.cattle.io/projectId: "abcde:12345"
  name: my-namespace
```
